api_platform:
    title: API Platform
    version: 1.0.0
    formats:
        json: [ 'application/json' ]
    error_formats:
        jsonproblem: [ 'application/problem+json' ]
        jsonld: [ 'application/ld+json' ]
    defaults:
        pagination_enabled: false
        normalization_context:
            skip_null_values: false
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
