framework:
    messenger:
        transports:
            high:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        high:
                            binding_keys: [high]
            medium:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        medium:
                            binding_keys: [medium]
            low:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        low:
                            binding_keys: [low]
        routing:
            App\Message\PublishScheduledPublicationsMessage: high
