parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $linkedinClientId: '%env(LINKEDIN_CLIENT_ID)%'
            string $linkedinClientSecret: '%env(resolve:LINKEDIN_CLIENT_SECRET)%'
            string $linkedinCallbackUrl: '%env(resolve:LINKEDIN_CALLBACK_URL)%'
            string $linkedinApiUrl: '%env(resolve:LINKEDIN_API_URL)%'
            string $linkedinLoginUrl: '%env(resolve:LINKEDIN_LOGIN_URL)%'
#
            string $twitterCallbackUrl: '%env(resolve:TWITTER_CALLBACK_URL)%'
            string $twitterApiUrl: '%env(resolve:TWITTER_API_URL)%'
            string $twitterApiXUrl: '%env(resolve:TWITTER_API_X_URL)%'
            string $twitterApiKey: '%env(resolve:TWITTER_API_KEY)%'
            string $twitterApiSecret: '%env(resolve:TWITTER_API_SECRET)%'

            string $facebookClientId: '%env(FACEBOOK_CLIENT_ID)%'
            string $facebookClientSecret: '%env(FACEBOOK_CLIENT_SECRET)%'
            string $facebookCallbackUrl: '%env(FACEBOOK_CALLBACK_URL)%'
            string $facebookApiUrl: '%env(FACEBOOK_API_URL)%'
            string $facebookLoginUrl: '%env(FACEBOOK_LOGIN_URL)%'

            string $encryptionKey: '%env(ENCRYPTION_KEY)%'
            string $frontUrl: '%env(FRONT_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'