parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $backUrl: '%env(resolve:BACK_URL)%'
            string $frontUrl: '%env(resolve:FRONT_URL)%'
            string $callbackUrl: '%env(resolve:CALLBACK_URL)%'
            string $projectRoot: '%env(resolve:PROJECT_ROOT)%'

            string $facebookClientId: '%env(resolve:FACEBOOK_CLIENT_ID)%'
            string $facebookClientSecret: '%env(resolve:FACEBOOK_CLIENT_SECRET)%'
            string $facebookApiUrl: '%env(resolve:FACEBOOK_API_URL)%'
            string $facebookLoginUrl: '%env(resolve:FACEBOOK_LOGIN_URL)%'

            string $linkedinClientId: '%env(resolve:LINKEDIN_CLIENT_ID)%'
            string $linkedinClientSecret: '%env(resolve:LINKEDIN_CLIENT_SECRET)%'
            string $linkedinApiUrl: '%env(resolve:LINKEDIN_API_URL)%'
            string $linkedinLoginUrl: '%env(resolve:LINKEDIN_LOGIN_URL)%'
            
            string $twitterApiUrl: '%env(resolve:TWITTER_API_URL)%'
            string $twitterApiKey: '%env(resolve:TWITTER_API_KEY)%'
            string $twitterApiSecret: '%env(resolve:TWITTER_API_SECRET)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Serializer\GroupsContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\GroupsContextBuilder.inner' ]
        autoconfigure: false

